name: Check Android Builds Work
on:
  push:
    branches: [ main ]
   # paths:
   #   - android-sdk/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: main
    steps:
    - uses: actions/checkout@v2
    - name: check java build still works
      run: |
        curl -X POST 'https://api.github.com/repos/Solipath/Android-Solipath-Example/actions/workflows/_build.yml/dispatches' \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: Bearer ${{ secrets.GITHUBREPOSECRET }}' \
        -d '{"ref":"${{matrix.version}}"}'
