name: Check Java Builds Work
on:
  push:
    branches: [ main ]
    # paths:
    #   - java/**
    #   - gradle/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 17
          - version: 21
    steps:
    - uses: actions/checkout@v2
    - name: check java build still works
      run: |
        curl -X POST 'https://api.github.com/repos/Solipath/Java-Gradle-Solipath-Example/actions/workflows/_build.yml/dispatches' \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: Bearer ${{ secrets.GITHUBREPOSECRET }}' \
        -d '{"ref":"${{matrix.version}}"}'