name: Check SBT Builds Work
on:
  push:
    branches: [ main ]
    paths:
      - sbt/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.9"
    steps:
    - uses: actions/checkout@v2
    - name: check go build still works
      run: |
        curl -X POST 'https://api.github.com/repos/Solipath/Scala-SBT-Solipath-Example/actions/workflows/_build.yml/dispatches' \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: Bearer ${{ secrets.GITHUBREPOSECRET }}' \
        -d '{"ref":"${{matrix.version}}"}'
